"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import ReportView from "@/components/ReportView";
import PrintButton from "@/components/PrintButton";
import { AppShell, StepRail, ArrowUpIcon, SparkIcon } from "@/components/AppShell";

type Message = { role: "user" | "ai"; content: string };
const TOPICS = [
  { title: "정기 업무", desc: "매일·매주 반복하는 일", icon: "↻", color: "blue" },
  { title: "장비·점검", desc: "장비를 다루고 확인하는 일", icon: "◈", color: "purple" },
  { title: "교육·안내", desc: "다른 사람에게 알려주는 일", icon: "◌", color: "green" },
  { title: "문제 해결", desc: "예외 상황에 대응하는 일", icon: "!", color: "orange" },
];
const STARTERS = ["처음부터 순서대로 설명해볼게요", "가장 자주 하는 업무예요", "주의할 점부터 말해볼게요"];
const GOALS = ["전체 흐름", "초보자용 순서", "실수·주의사항"];

export default function InterviewPage() {
  const router = useRouter();
  const [checking, setChecking] = useState(true); const [email, setEmail] = useState<string | null>(null);
  const [started, setStarted] = useState(false); const [topic, setTopic] = useState(""); const [goal, setGoal] = useState("전체 흐름"); const [topicStep, setTopicStep] = useState(1);
  const [starting, setStarting] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false);
  const [document, setDocument] = useState<string | null>(null); const [generating, setGenerating] = useState(false); const [slug, setSlug] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [toast, setToast] = useState<string | null>(null);
  useEffect(() => { if (new URLSearchParams(window.location.search).get("preview") === "1") { setEmail("joon@example.com"); setTopic("장비·점검"); setGoal("초보자용 순서"); setStarted(true); setMessages([{ role: "ai", content: "좋아요. 이 업무를 처음 하는 사람이 가장 먼저 해야 할 일은 무엇인가요?" }, { role: "user", content: "먼저 장비 상태와 주변 안전부터 확인해요." }, { role: "ai", content: "잘하고 있어요. 확인이 끝난 뒤에는 어떤 순서로 진행하나요?" }]); setChecking(false); return; } supabase.auth.getUser().then(({ data }) => { if (!data.user) router.replace("/login"); else { setEmail(data.user.email ?? null); setChecking(false); } }); }, [router]);
  const auth = async () => { const { data } = await supabase.auth.getSession(); return { Authorization: `Bearer ${data.session?.access_token}` }; };
  const start = async () => { if (!topic.trim()) return; setStarting(true); try { const res = await fetch("/api/interview", { method: "POST", headers: { "Content-Type": "application/json", ...(await auth()) }, body: JSON.stringify({ messages: [{ role: "user", content: `업무 주제: ${topic}\n정리하고 싶은 범위: ${goal}` }] }) }); const data = await res.json(); setMessages([{ role: "ai", content: data.question }]); setStarted(true); } finally { setStarting(false); } };
  const sendText = async (text = input) => { if (!text.trim() || loading) return; const next = [...messages, { role: "user", content: text } as Message]; setMessages(next); setInput(""); setLoading(true); try { const res = await fetch("/api/interview", { method: "POST", headers: { "Content-Type": "application/json", ...(await auth()) }, body: JSON.stringify({ messages: next.map(m => ({ role: m.role === "ai" ? "assistant" : "user", content: m.content })) }) }); const data = await res.json(); setMessages([...next, { role: "ai", content: data.question }]); } catch { setMessages([...next, { role: "ai", content: "잠시 문제가 생겼어요. 다시 한 번 시도해주세요." }]); } finally { setLoading(false); } };
  const generate = async () => { setGenerating(true); setError(null); try { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace("/login"); return; } const res = await fetch("/api/generate-doc", { method: "POST", headers: { "Content-Type": "application/json", ...(await auth()) }, body: JSON.stringify({ messages }) }); if (res.status === 429) { setError((await res.json()).error); return; } const { document: docContent } = await res.json(); const { data: session, error: sessionError } = await supabase.from("sessions").insert({ title: topic || "인수인계 인터뷰", status: "done", user_id: user.id }).select().single(); if (sessionError) throw sessionError; await supabase.from("messages").insert(messages.map(m => ({ session_id: session.id, role: m.role, content: m.content }))); const { data: doc, error: docError } = await supabase.from("documents").insert({ session_id: session.id, content: docContent, user_id: user.id, topic }).select().single(); if (docError) throw docError; setDocument(docContent); setSlug(doc.share_slug); } catch { setError("문서 생성 중 문제가 생겼어요."); } finally { setGenerating(false); } };
  const reset = () => { setStarted(false); setMessages([]); setTopic(""); setGoal("전체 흐름"); setTopicStep(1); setDocument(null); setSlug(null); setError(null); };
  const progress = Math.min(92, Math.max(18, messages.length * 13)); const lastAi = useMemo(() => [...messages].reverse().find(m => m.role === "ai")?.content, [messages]);
  if (checking) return <div className="min-h-screen bg-white" />;
  if (!started) return <AppShell eyebrow="NEW DOCUMENT" title="무슨 일을 남겨볼까요?" description="카드를 고르면 다음 단계가 열려요. 막히는 일 없이 하나씩 시작해보세요.">
    <div className="toss-flow"><StepRail active={1}/><div className="toss-flow__top"><div><span className="flow-counter">STEP {topicStep} / 3</span><h2>{topicStep === 1 ? "업무의 종류를 골라주세요." : topicStep === 2 ? "어떤 업무인지 알려주세요." : "어디에 집중할까요?"}</h2><p>{topicStep === 1 ? "가장 가까운 카드를 선택하면 돼요." : topicStep === 2 ? "정확한 이름이 아니어도 괜찮아요." : "문서에 담을 범위를 선택해보세요."}</p></div><div className="flow-progress"><i style={{ width: `${topicStep * 33.33}%` }}/></div></div>
    <div className="toss-flow__body">
      {topicStep === 1 && <div className="topic-choices topic-choices--large">{TOPICS.map(item => <button key={item.title} className={topic === item.title ? "is-selected" : ""} onClick={() => { setTopic(item.title); setTopicStep(2); }}><b className={`topic-icon topic-icon--${item.color}`}>{item.icon}</b><span><strong>{item.title}</strong><small>{item.desc}</small></span><i>→</i></button>)}</div>}
      {topicStep === 2 && <div className="flow-step-panel"><div className="selected-topic"><span className="selected-topic__icon">{TOPICS.find(t => t.title === topic)?.icon || "✦"}</span><div><small>선택한 업무 유형</small><b>{topic || "직접 입력"}</b></div><button onClick={() => setTopicStep(1)}>변경</button></div><label>업무 이름을 적어주세요</label><div className="topic-input topic-input--large"><input autoFocus value={TOPICS.some(t => t.title === topic) ? "" : topic} onChange={e => setTopic(e.target.value)} onKeyDown={e => e.key === "Enter" && topic.trim() && setTopicStep(3)} placeholder="예: 개인화기 손질 및 점검"/><button disabled={!topic.trim()} onClick={() => setTopicStep(3)}><ArrowUpIcon/></button></div><p className="field-hint">팀에서 부르는 이름이나 기억하기 쉬운 말이면 충분해요.</p></div>}
      {topicStep === 3 && <div className="flow-step-panel"><div className="selected-topic"><span className="selected-topic__icon">{TOPICS.find(t => t.title === topic)?.icon || "✦"}</span><div><small>정리할 업무</small><b>{topic}</b></div><button onClick={() => setTopicStep(2)}>변경</button></div><label>어떤 내용을 중심으로 남길까요?</label><div className="goal-cards">{GOALS.map(item => <button key={item} className={goal === item ? "is-selected" : ""} onClick={() => setGoal(item)}><span>{goal === item ? "✓" : ""}</span><b>{item}</b><small>{item === "전체 흐름" ? "처음부터 끝까지 한 번에" : item === "초보자용 순서" ? "처음 하는 사람도 따라오게" : "실수하기 쉬운 포인트 중심"}</small></button>)}</div><button className="topic-next button button--primary" onClick={start} disabled={starting}>{starting ? "인터뷰 준비 중..." : "이 업무로 인터뷰 시작하기"}<ArrowUpIcon/></button></div>}
    </div><div className="toss-flow__footer"><button className="flow-back" disabled={topicStep === 1} onClick={() => setTopicStep(topicStep - 1)}>← 이전 단계</button><span><SparkIcon/> 답변은 언제든 수정할 수 있어요</span></div></div>
  </AppShell>;
  return <AppShell eyebrow={document ? "DOCUMENT READY" : "INTERVIEW · STEP 2 OF 3"} title={document ? "문서가 완성됐어요." : "이제 편하게 이야기해보세요."} description={document ? "대화에서 나온 경험을 한 장의 문서로 정리했어요." : `${topic}에 대해 알고 있는 만큼 답해주세요.`} action={!document && <button className="button button--ghost button--small" onClick={reset}>주제 다시 고르기</button>}><StepRail active={document ? 3 : 2}/>{!document ? <div className="interview-workspace"><div className="interview-progress"><div><span>이번 인터뷰</span><b>{progress}% 정리됨</b></div><div className="progress-track"><i style={{ width: `${progress}%` }}/></div></div><div className="interview-layout"><div className="chat-card"><div className="chat-card__top"><div className="interviewer"><span className="interviewer__avatar"><SparkIcon/></span><span><strong>ISIG 인터뷰어</strong><small>{topic} · {goal}</small></span></div><span className="live-status">대화 중</span></div><div className="chat-messages">{messages.map((m, i) => <div key={i} className={`chat-bubble chat-bubble--${m.role}`}>{m.content}</div>)}{loading && <div className="chat-bubble chat-bubble--ai loading-dots"><i/><i/><i/></div>}</div>{!loading && lastAi && <div className="quick-replies"><span>빠른 답변</span>{STARTERS.map(item => <button key={item} onClick={() => sendText(item)}>{item}</button>)}</div>}<div className="chat-compose"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === "Enter" && sendText()} placeholder="답변을 입력하세요" disabled={loading}/><button className="send-button" onClick={() => sendText()} disabled={loading || !input.trim()}><ArrowUpIcon/></button></div></div><aside className="interview-aside"><div className="aside-card aside-card--blue"><h3><SparkIcon/> 지금 듣고 있어요</h3><p>짧은 문장도 좋아요. 답변할수록 다음 질문이 더 정확해져요.</p></div><div className="aside-card"><h3>이 정도면 충분한가요?</h3><p>핵심 흐름이 정리됐다면 지금 문서로 만들 수 있어요.</p><button className="button button--soft button--small generate-button" onClick={generate} disabled={generating}>{generating ? "문서를 정리하는 중..." : "여기까지 문서로 만들기"}</button>{error && <p className="error-text">{error}</p>}</div></aside></div></div> : <div className="doc-result"><div className="doc-paper"><ReportView content={document}/><p className="doc-paper__meta">작성자: {email} · {new Date().toLocaleString("ko-KR")}</p></div><div className="doc-actions"><PrintButton/>{slug && <button className="button button--soft button--small" onClick={() => { navigator.clipboard.writeText(`${window.location.origin}/docs/${slug}`); setToast("공유 링크를 복사했어요"); }}>링크 공유하기</button>}<button className="button button--primary button--small" onClick={() => router.push("/home")}>내 문서로 이동</button></div></div>}{toast && <div className="toast">{toast}</div>}</AppShell>;
}
