"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import MarkdownDoc from "@/components/MarkdownDoc";
import PrintButton from "@/components/PrintButton";
import { AppShell, StepRail, ArrowUpIcon, SparkIcon } from "@/components/AppShell";

type Message={role:"user"|"ai";content:string};
export default function InterviewPage(){
 const router=useRouter(); const [checking,setChecking]=useState(true); const [email,setEmail]=useState<string|null>(null); const [started,setStarted]=useState(false); const [topic,setTopic]=useState(""); const [starting,setStarting]=useState(false); const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [document,setDocument]=useState<string|null>(null); const [generating,setGenerating]=useState(false); const [slug,setSlug]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [toast,setToast]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user)router.replace("/login");else{setEmail(data.user.email??null);setChecking(false)}})},[router]);
 const auth=async()=>{const {data}=await supabase.auth.getSession();return {Authorization:`Bearer ${data.session?.access_token}`}};
 const start=async()=>{if(!topic.trim())return;setStarting(true);try{const res=await fetch("/api/interview",{method:"POST",headers:{"Content-Type":"application/json",...(await auth())},body:JSON.stringify({messages:[{role:"user",content:`업무 주제: ${topic}`}]})});const data=await res.json();setMessages([{role:"ai",content:data.question}]);setStarted(true)}finally{setStarting(false)}};
 const send=async()=>{if(!input.trim()||loading)return;const next=[...messages,{role:"user",content:input} as Message];setMessages(next);setInput("");setLoading(true);try{const res=await fetch("/api/interview",{method:"POST",headers:{"Content-Type":"application/json",...(await auth())},body:JSON.stringify({messages:next.map(m=>({role:m.role==="ai"?"assistant":"user",content:m.content}))})});const data=await res.json();setMessages([...next,{role:"ai",content:data.question}])}catch{setMessages([...next,{role:"ai",content:"잠시 문제가 생겼어요. 다시 한 번 시도해주세요."}])}finally{setLoading(false)}};
 const generate=async()=>{setGenerating(true);setError(null);try{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const res=await fetch("/api/generate-doc",{method:"POST",headers:{"Content-Type":"application/json",...(await auth())},body:JSON.stringify({messages})});if(res.status===429){setError((await res.json()).error);return}const {document:docContent}=await res.json();const {data:session,error:sessionError}=await supabase.from("sessions").insert({title:topic||"인수인계 인터뷰",status:"done",user_id:user.id}).select().single();if(sessionError)throw sessionError;await supabase.from("messages").insert(messages.map(m=>({session_id:session.id,role:m.role,content:m.content})));const {data:doc,error:docError}=await supabase.from("documents").insert({session_id:session.id,content:docContent,user_id:user.id,topic}).select().single();if(docError)throw docError;setDocument(docContent);setSlug(doc.share_slug)}catch{setError("문서 생성 중 문제가 생겼어요.")}finally{setGenerating(false)}};
 const reset=()=>{setStarted(false);setMessages([]);setTopic("");setDocument(null);setSlug(null);setError(null)};
 if(checking)return <div className="min-h-screen bg-white"/>;
 if(!started)return <AppShell eyebrow="NEW DOCUMENT" title="어떤 업무를 정리할까요?" description="주제만 알려주시면, ISIG가 필요한 질문을 준비할게요."><div className="topic-layout"><div className="topic-card"><StepRail active={1}/><div className="topic-card__icon"><SparkIcon/></div><h2>업무의 이름을<br/><span>편하게 적어주세요.</span></h2><p>예를 들면 ‘신병 교육’, ‘장비 점검’,<br/>‘월말 정산’처럼요.</p><div className="topic-input"><input autoFocus value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==="Enter"&&start()} placeholder="예: 개인화기 손질 및 점검"/><button onClick={start} disabled={starting||!topic.trim()}><ArrowUpIcon/></button></div><small>대화가 시작되면 언제든 주제를 바꿀 수 있어요.</small></div><div className="topic-side"><div><b>왜 주제부터 물어볼까요?</b><p>업무마다 꼭 필요한 질문이 다르기 때문이에요. 주제를 알면 더 짧고 정확한 대화가 가능해져요.</p></div><div className="topic-side__quote">“잘 설명하려고 하지 않아도<br/><strong>괜찮아요.</strong> 제가 물어볼게요.”</div></div></div></AppShell>;
 return <AppShell eyebrow={document?"DOCUMENT READY":"INTERVIEW IN PROGRESS"} title={document?"문서가 완성됐어요.":topic} description={document?"대화에서 나온 경험을 한 장의 문서로 정리했어요.":"아는 만큼 편하게 답해보세요. 짧게 말해도 충분해요."} action={!document&&<button className="button button--ghost button--small" onClick={reset}>주제 변경</button>}><StepRail active={document?3:2}/>{!document?<div className="interview-layout"><div className="chat-card"><div className="chat-card__top"><strong>ISIG 인터뷰어</strong><span>대화 중</span></div><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`chat-bubble chat-bubble--${m.role}`}>{m.content}</div>)}{loading&&<div className="chat-bubble chat-bubble--ai loading-dots"><i/><i/><i/></div>}</div><div className="chat-compose"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="답변을 입력하세요" disabled={loading}/><button className="send-button" onClick={send} disabled={loading||!input.trim()}><ArrowUpIcon/></button></div></div><aside className="interview-aside"><div className="aside-card aside-card--blue"><h3><SparkIcon/> 이렇게 진행돼요</h3><p>경험을 듣고, 빠진 내용을 확인한 뒤, 읽기 쉬운 순서로 정리해요.</p></div><div className="aside-card"><h3>충분히 이야기했나요?</h3><p>지금까지의 대화만으로도 문서를 만들 수 있어요.</p><button className="button button--soft button--small generate-button" onClick={generate} disabled={generating}>{generating?"정리하는 중...":"문서로 정리하기"}</button>{error&&<p className="error-text">{error}</p>}</div></aside></div>:<div className="doc-result"><div className="doc-paper"><div className="doc-paper__label">완성된 인수인계 문서</div><MarkdownDoc content={document}/><p className="doc-paper__meta">작성자: {email} · {new Date().toLocaleString("ko-KR")}</p></div><div className="doc-actions"><PrintButton/>{slug&&<button className="button button--soft button--small" onClick={()=>{navigator.clipboard.writeText(`${window.location.origin}/docs/${slug}`);setToast("공유 링크를 복사했어요")}}>링크 공유하기</button>}<button className="button button--primary button--small" onClick={()=>router.push("/home")}>내 문서로 이동</button></div></div>}{toast&&<div className="toast">{toast}</div>}</AppShell>;
}
